# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20161214_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_name',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
