# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_auto_20161214_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='style',
            field=models.CharField(blank=True, choices=[(b'1', b'StandardHost'), (b'2', b'TwoHosts'), (b'3', b'ThreeHosts'), (b'4', b'FourHosts')], default=b'1', max_length=20),
        ),
    ]
