# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_auto_20170216_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='hosts.Device'),
        ),
    ]
